### ISSUE TITLE
setUserProperties is not exported

### ISSUE THREAD

**Issue by baptistejamin** [amplitude/Amplitude-TypeScript#110]
Hello!

We are currently migrating to this project.

I just noticed that `setUserProperties` is not exported here: https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/index.ts#L17

Is there any reason to export `setUserId` but not `setUserProperties` ?

**Comment by qingzhuozhen** [comment]
Hi @baptistejamin Thanks for the feedback. To set user properties, you can actually use the identify method, set the user properties via Identify method. Some example in https://developers.amplitude.com/docs/typescript-browser-beta#user-properties. That's why we didn't add the setUserProperties call earlier. Would you prefer a call like setUserProperties more or if the current solution is also good for you? 

Also while you are currently migrating to use this SDK, we would love to learn how everything is going for you and if any thing more we could do. Thank you. 

cc @kevinpagtakhan @dnshi

**Comment by baptistejamin** [comment]
It's kinda weird to provide all the previous methods such as `logEvent` or `setUserId` but not this one :)
