### ISSUE TITLE
Typescript SDK and the web attribution

### ISSUE THREAD

**Issue by FQ400** [amplitude/Amplitude-TypeScript#134]
## Summary

We try to switch to the Typescript-SDK for the browser from the JS-SDK and we wonder how to configure new client for the web attribution? 

With the JS-SDK we used something like this:
```
  amplitude.getInstance().init(AMPLITUDE_API_KEY, '', {
    platform: 'Web',
    includeReferrer: true,
    includeUtm: true,
    includeGclid: true,
  });
```
Here are the docs from the JS version: https://www.docs.developers.amplitude.com/data/sdks/javascript/#web-attribution

I checked [the code](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/browser-client.ts#L54) as well and found that there is an `attribution` key in the options that can be passed to the `init` function. What do I have to pass?

**Comment by kevinpagtakhan** [comment]
Hi @FQ400, thanks for submitting an issue! Since v0.6.1, this SDK tracks web attribution by default. We will soon publish the docs regarding this and will add the link here. Here are the optional keys in attribution options: https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/config.ts#L80-L86. Quick info on them:
|Option|Description|
|-|-|
`attribution.disabled`|Disables web attribution tracking. Default: `false`
`attribution.initialEmptyValue`|Defines the initial value of attribution parameters if initial touch is organic/direct traffic. Default: `"EMPTY"`
`attribution.trackNewCampaigns`|Tracks new attribution parameters mid-session. If false, attribution parameters are only tracked at the start of a new session. Default: `false`
`attribution.excludeReferrers`|Adds exception to `trackNewCampaigns` based on campaign referrer. Default: `[]`
`attribution.trackPageViews`|Includes a page view event with basic page info as event properties. Default: `false`<br><br>NOTE: The page view events count against your quota

**Comment by kevinpagtakhan** [comment]
@FQ400 here are out docs for web attribution for `@amplitude/analytics-browser` package: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#web-attribution

**Comment by FQ400** [comment]
@kevinpagtakhan Thank you for the response. We can work with that. 😄

**Comment by alexblack** [comment]
Hi, that link seems broken now :(. Could you clarify a bit? I have the same question about the same options that we use in `amplitude-js`, I don't see them in this sdk nor the attribution sdk:

```
    includeFbclid: true,
    includeGclid: true,
    includeReferrer: true,
    includeUtm: true,
```

**Comment by kevinpagtakhan** [comment]
These are enabled by default :) Can you check if this doc helps? https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#web-attribution

**Comment by alexblack** [comment]
Thanks!  Do we need the web attribution plugin for them to be enabled by default?
