### ISSUE TITLE
Question: Is "set" suppose to override values?

### ISSUE THREAD

**Issue by Sicofonia** [amplitude/Amplitude-TypeScript#223]
I want to record property values for settings that can be toggled (such as enable notifications, which can only have two possible values, `true` or `false`).

Once I set the property, upon subsequent changes in values I can see the recorded value has not changed in Amplitude (for example, changing from `true` to `false`). Is this by design?

**Comment by kevinpagtakhan** [comment]
Hi @Sicofonia! Thank you for using amplitude. `Identify.set` method should update on each call. The behavior described above sounds more like `Identify.setOnce`. Do you have a code sample that you can share?

**Comment by Sicofonia** [comment]
Hi @kevinpagtakhan , thanks for the speedy reply.

I do. Take a look at this snippet:
`
let isInitialized = false;
const identifyObj = new Identify();

export async function setUserPropertiesAsync(key, values) {
   if (!isInitialized) {
      throw 'Amplitude is not initialized';
   }
   await identifyObj.set(key, values);
   await identify(identifyObj);
}
`

And this is an example of how this function is called elsewhere:
`
await setUserPropertiesAsync('notifications', isEnabled);
`

**Comment by yuhao900914** [comment]
Hi @Sicofonia, the `identify.set` method is able to overwrite the property value. 
But I just noticed. It somehow needs you to refresh the dashboard to get the updated value in the user properties section. 
The user properties section shows the old property value, even if there has a new Event Stream comes in which we reset the property.
This is the user properties panel I mentioned:
<img width="1243" alt="Screen Shot 2022-09-19 at 1 54 42 PM" src="https://user-images.githubusercontent.com/13028329/191114712-a535c429-29fc-416a-a317-75f95a1976df.png">
You can see in the raw data section, that the notification value has already been set to be `false`.
But the value in the user properties section is still `true`. 
<img width="1060" alt="Screen Shot 2022-09-19 at 1 59 37 PM" src="https://user-images.githubusercontent.com/13028329/191115728-9485cb7c-9989-4d4e-89be-3373a836e1c1.png">

If you are facing the same situation, I will contact our other team and see if that's by design. 
Otherwise, I might need to dig into this issue more.

**Comment by yuhao900914** [comment]
Hi @Sicofonia,
I think that is by design, please check the code [here](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-core/src/identify.ts#L99).
If you send multiple identify.set('notification', value) in roll. We will only capture the first one. 
But if the local memory got refreshed, you are able to reset the value of the property.

**Comment by Sicofonia** [comment]
Hi @yuhao900914 thanks a lot for chipping in. That explains it.

So if I wanted to change the value of a property already set, what method in the library should I use? (i.e. a user who disables notifications, after he/she enabled it in my case).

**Comment by Sicofonia** [comment]
Thanks so much @kevinpagtakhan , I now realized what I was doing wrong. Didn't occur I had to instantiate the object at that level. I can confirm on my end that your suggestion is helping me achieve the desired behavior.

I close the question now as it has been answered. Thanks once again :-)
