### ISSUE TITLE
Device ID changing with Proxy Implementation

### ISSUE THREAD

**Issue by blairmason** [amplitude/Amplitude-TypeScript#262]
## Summary
After updating the init of the SDK with a dummy key of '00000000000000000000000000000000' and a serverUrl that corresponds to our new proxy, we noticed that the Device ID changed for every user after this change. Is this expected?

**Comment by kevinpagtakhan** [comment]
Hi @blairmason! Thank you for choosing Amplitude! To clarify, did the device ID change one time at the time of the API key switch or is it changing continuously since the API key switch?

For the Browser SDK, the device ID is stored in your cookie storage keyed with a string containing your a substring of your API key. After switching to a new API key, the SDK may not find the cookie for the new API key, and will generate a new device ID one time.

**Comment by blairmason** [comment]
Yes, the Device ID changed one time at the time of the API key switch.

**Comment by kevinpagtakhan** [comment]
@blairmason Yes this is expected behavior. The storage is keyed by a string containing the API key (unique per project) to allow multiple instances of the SDK to run simultaneously.
