### ISSUE TITLE
wrong OS version for in-app browsers

### ISSUE THREAD

**Issue by BeepYoung** [amplitude/Amplitude-TypeScript#265]
OS version generation based on user-agent so it works not properly

## Expected Behavior

iPhone like OS should appear

## Current Behavior

Instagram version in OS field

<img width="473" alt="image" src="https://user-images.githubusercontent.com/14242296/199536486-aa21de48-51f8-4ce3-9a68-7d463d03e37e.png">

user-agent: ```Mozilla/5.0 (iPhone; CPU iPhone OS
15_6_1 like Mac OS X) AppleWebKit/
605.1.15 (HTML, like Gecko) Mobile/
15E148 Instagram 259.0.0.18.104
(iPhone12,8; iOS 15_6_1; en_US; en;
scale=2.00; 750x1334; 413505119)```

## Steps to Reproduce

1.  open instagram 
2. track some event
3. go to `user look-up` in amplitude ui tools

## Environment
- typescript sdk version - "@amplitude/analytics-browser": "^1.4.0"
- Installation Method: npm

**Comment by liuyang1520** [comment]
Hi @BeepYoung , thanks for submitting this! We are using a forked version of [ua-parser-js](https://github.com/amplitude/ua-parser-js) to handle the user agents. I have search on the original source, and didn't find [any suspicious similar issues](https://github.com/faisalman/ua-parser-js/issues?q=is%3Aissue+Instagram).

For the step 2 mentioned in description, does it mean to use Instagram embedded browser to open your web page (installed Amplitude TypeScript SDK on the page)?

**Comment by BeepYoung** [comment]
Hi @liuyang1520 ! Yes, we're on the same page about step 2

**Comment by kevinpagtakhan** [comment]
Hi @BeepYoung, thank you for choosing Amplitude. We designed the Browser SDK to use browser name and browser version to fill in Amplitude's built-in user properties `OS name` and `OS version`. If you prefer to use the true OS name/version, you can create/use a plugin to overwrite the values we provide. We can help create this plugin if you like. Otherwise, some of our customers had requests for custom behavior like this and we have published the plugin solution we proposed here: https://github.com/amplitude/Amplitude-TypeScript/tree/main/examples/plugins for inspiration.

**Comment by BeepYoung** [comment]
Thank!
