### ISSUE TITLE
Overwrite event properties 

### ISSUE THREAD

**Issue by empiteranga** [amplitude/Amplitude-TypeScript#470]
Im using `@amplitude/analytics-react-native` in react native app. when using same event , it automatically update previous event property with new event event property.

here is my code. in eventData object I'm passing eventId property 

```
export const postAmplitude = async (
  event: string,
  userId: string,
  eventId: string,
) => {
  const eventData = {
    app_version: DeviceInfo.getVersion(),
    build_number: DeviceInfo.getBuildNumber(),
    eventId: eventId,
  };

  if (userId) {
    const result = await init(AMPLITUDE_ID.DEV, userId).promise;
    if (event) {
      setTimeout(() => {
        track(event, eventData);
      }, 5000);
    }
  } else {
    const result = await track(event, eventData).promise;
  }
};
```

**Comment by justin-fiedler** [comment]
Hi @empiteranga, thanks for choosing Amplitude. I am not sure I fully understand the issue but noticed a couple things.

For your main problem, I believe you are trying to set some event "fields" (not event properties). See [docs how to track an event with event properties](https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/#tracking-an-event).

In this case I believe you want to use this which sets the fields at the `event` level rather than `event.event_properties`.

```
const result = await track({ ...eventData, event_type: event}).promise;
```

Or use the third argument for EventOptions to achieve the same.

```
const result = await track(e, undefined, eventData}).promise;
```

See definition of [track](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-core/src/core-client.ts#L55) and [EventOptions](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/base-event.ts#L12) for more details.

I also wanted to call out that [init()](https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/#initialize-the-sdk) is designed to only be called once at start up. To change userId you can use [setUserId()](https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/#custom-user-id) instead.

Hope this helps!
