### ISSUE TITLE
Bug: `trackingOptions` doesn't work

### ISSUE THREAD

**Issue by FirstVertex** [amplitude/Amplitude-TypeScript#541]
## Expected Behavior

The ip address, language, and platform should not be logged when they are set to false in the init `trackingOptions`, as per [documentation](https://www.docs.developers.amplitude.com/data/sdks/browser-2/#optional-tracking).

## Current Behavior

The ip address, language, and platform were tracked, when they were explicitly disabled via the `trackingOptions` input.

## Steps to Reproduce

1. Set false the 3 available options in the `trackingOptions` 2nd parameter to init documented here:
https://www.docs.developers.amplitude.com/data/sdks/browser-2/#optional-tracking

```
amplitude.init(API_KEY, {
  trackingOptions: {
    ipAddress: false,
    language: false,
    platform: false,
  },
});
```

2. call `amplitude.track()` to add any event to the Dashboard

3. visit the Amplitude Dashboard page and view the newly tracked event

4. Notice that the ip address, language, and platform are all logged, even though the call to init set these to false

## Environment
- JS SDK Version: `"@amplitude/analytics-browser": "~2.2.0"`
- Installation Method:  `npm i @amplitude/analytics-browser`
- Browser and Version: Chrome

**Comment by Mercy811** [comment]
Hi @FirstVertex, this should be [fixed in `v2.1.3`](https://github.com/amplitude/Amplitude-TypeScript/releases/tag/%40amplitude%2Fanalytics-browser%402.1.3). I did a local test with your configuration using the [example project](https://github.com/amplitude/Amplitude-TypeScript/tree/main/examples/browser/react-app) and there is no disabled tracking options. Here is my payload:
```
{
    "user_id": "example.react.user@amplitude.com",
    "device_id": "d82c3794-3004-418c-9236-33085bc99f8a",
    "session_id": 1698779861088,
    "time": 1698780907285,
    "insert_id": "944ad92d-bf9c-4667-abf8-a8ede3597a67",
    "event_type": "Button Click",
    "event_properties": {
        "name": "App"
    },
    "event_id": 15,
    "library": "amplitude-ts/2.2.0",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
}
```
I would suggest to check your `package-lock.json` and `library` field of events on Dashboard to make sure that you are using `v2.1.3` and above.
