### ISSUE TITLE
can latest version present Device Type iPhone 15?

### ISSUE THREAD

**Issue by 2sem** [amplitude/Amplitude-TypeScript#597]
## Expected Behavior

Device Type: iPhone 15 Pro Max

## Current Behavior

Device Type: -
![스크린샷 2023-10-06 오후 12 23 49](https://github.com/amplitude/Amplitude-TypeScript/assets/16129260/2be49a81-c5b0-4240-96a8-b78fd2ec55ad)

## Steps to Reproduce

1. iPhone 15 Pro Max
2. run app
3. see log #Device Type#
4.

## Environment
- JS SDK Version: 2.16.2
- Installation Method: yarn
- Browser and Version: iOS

**Comment by Mercy811** [comment]
Hi @2sem thanks for choosing Amplitude. The library `amplitude-react-native/2.16.2` refers to the [maintenance React Native SDK](https://www.docs.developers.amplitude.com/data/sdks/react-native/). Please open an issue in this [repo](https://github.com/amplitude/Amplitude-ReactNative) next time. It helps us keep track of issues from different SDKs. 

Device type is generated and mapped on the backend using a device mapping dictionary. It turns out that the dictionary is not up to date and should not be a bug of the SDK. It should be fixed soon.

**Comment by Mercy811** [comment]
Hi @2sem, I just merged the PRs to update the device mapping. It should take several minutes/hours to deploy.

**Comment by 2sem** [comment]
Thanks for your answer and the fix.

However your site's Github took me this repo.

<img width="796" alt="스크린샷 2023-10-07 오전 10 21 27" src="https://github.com/amplitude/Amplitude-TypeScript/assets/16129260/fdb51693-2efc-47c4-9adb-efca215652f9">

**Comment by Mercy811** [comment]
Hi @2sem, there are two React Native SDKs. The one you are using is the maintenance one. 
<img width="951" alt="image" src="https://github.com/amplitude/Amplitude-TypeScript/assets/31029607/b3df9fe2-e152-4398-b77c-8db1e955f362">
