### ISSUE TITLE
Amplitude instances

### ISSUE THREAD

**Issue by JulianRomana** [amplitude/Amplitude-TypeScript#84]
## Summary
Hi! We were using `amplitude-js` and now we are switching to `amplitude-ts`, but it seems that the whole `instances` concept has been removed.

## Motivations

We would like to be able to register different instances and send events to them independently. [Here](https://developers.amplitude.com/docs/javascript) is the previous doc, where we were able to perform this: 
```js
var instance1 = amplitude.getInstance().init("API_KEY"); // initializes default instance of Amplitude client
var instance2 = amplitude.getInstance("instance").init("API_KEY"); // initializes named instance of Amplitude client
```

Thanks!

**Comment by kevinpagtakhan** [comment]
Hi @JulianRomana. Thanks for submitting an issue. This is super helpful feedback. Your observations are correct, this new SDK does not support multiple version (at least not yet). Out of curiosity, what is the goal/s you are trying to achieve that multiple instances help with? Do you have multiple projects/api keys, or configuration, or http destination? Any info here would be super useful. Thanks so much.

**Comment by JulianRomana** [comment]
Hi @kevinpagtakhan! Thanks for responding so fast! 
Basically, we have a tracking library, where we want for some cases, send specific tracking events to a first amplitude project, and the others case will be to another one. This is motivated by having different tracking plan on a same web app.

Tell me if i'm not being clear, I will give you more precisions!

**Comment by kevinpagtakhan** [comment]
Hi @JulianRomana, support for multiple instances is not included in the first iteration of this new SDK, but we remain open to supporting multiple instances in the future. Out of curiosity, why did your team decide to maintain different tracking plans/projects for the same web app? Asking this to widen my understanding of customer use cases.

**Comment by JulianRomana** [comment]
Hi again! We want to be able to maintain a legacy tracking plan, so we have a long-term overview of the company's performance + the data and product team we still be able to use the data while in the mean time want to be able to plug new tracking plans thanks to every data we collected and what we improved!

I hope this helps! 

Also would you have an ETA for  such a feature?

**Comment by PaulFasola** [comment]
Hi @kevinpagtakhan,

On our end, we currently utilize an Amplitude instance distributed through Google Tag Manager across the company's properties. Additionally, we have a dedicated instance initialized within our app to keep control of the initialization properties, and the flow and to segregate data on a separate dashboard. The previous Amplitude library effectively handled this scenario, and transitioning from the Maintenance SDK to the current one presents challenges due to the absence of such a feature.

One specific issue is with the attribution event, where - for instance - setting utm_* properties only occurs once and is often associated with the global instance than our app's project. To work around this limitation, I am currently leveraging from the `@amplitude/plugin-web-attribution-browser` package, which I had. to the desired instance. However, this approach is suboptimal/hacky.

Therefore, it would greatly benefit us to have a `GetInstance`-like method there. Such a method would enable us to ensure that the correct data is sent to the appropriate instance/project.

**Comment by PaulFasola** [comment]
Hi @kevinpagtakhan,

On our end, we currently utilize an Amplitude instance distributed through Google Tag Manager across the company's properties. Additionally, we have a dedicated instance initialized within our app to keep control of the initialization properties, and the flow and to segregate data on a separate dashboard.

One specific issue we have while transitioning from the maintenance SDK to this one is the _attribution_ event where - for instance - setting utm_* properties **only occurs once per session** and is often associated with the global instance than our app's project, since the global one loads much faster. As far as I know from reading the documentation, there is no control over when to trigger it / for which instance. To work around this limitation, I am currently leveraging from the `@amplitude/plugin-web-attribution-browser` package, which I add to the desired instance. However, this approach is suboptimal/hacky. 

Using `createInstance` is not helping given the above scenario, would you have a better way in mind?
